Docs/improvements
SAP/project-sailor pull request #8
Opened 2021-03-04 15:47 UTC by cloudyday

2021-03-04 16:58 UTC, cloudyday commented
Hello again @SebastianWolf-SAP :-) 
I'm not 100% sure if the licensing with REUSE is done right here. 

Could you have a look at that last commit and let me know?

2021-03-05 08:03 UTC, SebastianWolf-SAP requested changes
I'd do a minor change to the copyright notice (see my suggestion). Moreover, please add the licensing section to your README. I guess, you're good to go afterwards.

2021-03-05 08:03 UTC, SebastianWolf-SAP commented on .reuse/dep5
> +Copyright:  2007-2021 by the Sphinx team.
If I recall correctly, you mentioned that you modified their original code. In this case, that should also be mentioned here:

```suggestion
Copyright:  2007-2021 by the Sphinx team. Modifications 2021 SAP SE or an SAP affiliate company and project "Sailor" contributors
```

2021-03-05 08:39 UTC, cloudyday commented
Thanks for the suggestions @SebastianWolf-SAP . I also saw that our copyright information was missing from the LICENSE file in the project root. I added that. 

Could you please check again?

2021-03-05 09:09 UTC, SebastianWolf-SAP approved these changes
LGTM, thanks for the changes.

2021-03-09 09:07 UTC, atrejut approved these changes

2021-03-09 09:55 UTC, merged